title: Video streaming platform
description: Idealizing a user and business-friendly video streaming platform
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

footer:
  links:
    - title: Twiter
      url: https://x.com/PaiVineet
    - title: LinkedIn
      url: https://www.linkedin.com/in/vineetpai/
    